### ISSUE TITLE
Translate the index.html to English 

### ISSUE THREAD

**Issue by marimendes** [marimendes/marimendes.github.io#1]

**Comment by GustavodaSilva** [comment]
Poderia me atribuir a esta tarefa?

**Comment by marimendes** [comment]
Claro

**Comment by Sharani** [comment]
<div id="google_translate_element"></div>
<script>
    function googleTranslateElementInit() {
        new google.translate.TranslateElement(
            {pageLanguage: 'pt'},
            'google_translate_element'
        );
    }
</script>
<script src="http://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
